[package]
name = "pisql_host_manager"
version = "0.0.1"
edition = "2021"
authors = [ "Piyush Datta <piyushdattaca@gmail.com>" ]

[dependencies]

[[bin]]
name = "pisql_host_manager"
path = "src/pisql_hm_main.rs"
