[package]
name = "pisql_server"
version = "0.0.1"
edition = "2021"
authors = [ "Piyush Datta <piyushdattaca@gmail.com>" ]

[dependencies]

[[bin]]
name = "pisql_server"
path = "src/pisql_server_main.rs"
